backend:
  name: git-gateway
  repo: open-innovations/weeknotes
  branch: main


media_folder: statics

collections:
  - label: Weeknotes
    label_singular: Weeknote
    name: weeknotes
    description: List of weeknotes
    folder: weeknotes
    extension: md
    create: true
    delete: false
    identifier_field: date
    fields:
      - label: Week Ending
        name: date
        widget: datetime
        default: ''
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Content
        name: body
        widget: markdown
        required: false