backend:
  name: github
  repo: open-innovations/weeknotes
  branch: main
  base_url: https://auth.open-innovations.org # Path to ext auth provider

media_folder: assets/uploads
logo_url: https://open-innovations.org/resources/images/logos/oi-square.svg

collections:
  - label: Weeknotes
    label_singular: Weeknote
    name: weeknotes
    description: List of weeknotes
    folder: weeknotes
    extension: md
    create: true
    delete: false
    identifier_field: date
    preview_path: /{{slug}}/
    summary: "{{slug}} - {{title}}"
    sortable_fields: ['date', 'draft']
    view_groups:
      - label: Drafts
        field: draft
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
      - label: Not Drafts
        field: draft
        pattern: false
    fields:
      - label: Title
        name: title
        widget: string
        # Not making this mandatory... Default to stringigied date
        required: false
      - label: Week Ending
        name: date
        widget: datetime
        default: ''
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Draft
        name: draft
        default: true
        widget: boolean
      - label: Content
        name: body
        widget: markdown
        required: false