name: Generate blank weeknote

"on":
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - shell: bash
        run: deno task create
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New blank weeknote
          file_pattern: src/weeknotes